/**
 * The transport — a pass-2 export becomes readings in this journal.
 *
 * The fixture is **generated by the Java that writes it on the phone**
 * (`tools/gen-export.sh`), for the same reason `apps/pixel/pass1/tests/
 * vectors.json` is: a hand-written fixture would agree with this reader by
 * construction and prove nothing about the pair. What is under test is the two
 * implementations meeting.
 */
import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { Journal, MemoryJournalStore, verifyLane } from "@orb/journal";
import { readObservation } from "@orb/observation";
import {
  GRANTS_OBSERVED_TYPE,
  ImportError,
  alertsFor,
  importExport,
  parseExport,
  project,
  raiseAlerts,
  type AlertRaised,
  type DeviceAuthorityReading,
} from "../src/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixture = () => readFile(join(here, "../../tests/fixtures/pass2-export.txt"), "utf8");

async function journal() {
  return Journal.open({ lane: "mac", device: "mac-01", store: new MemoryJournalStore() });
}

describe("an export written by the phone", () => {
  test("parses into events, keeping the phone's own identities", async () => {
    const events = parseExport(await fixture());
    assert.equal(events.length, 4);
    assert.ok(events.every((event) => event.lane === "grants"));
    assert.ok(events.every((event) => event.device === "Pixel 10a/stallion"));
  });

  test("verifies under the TypeScript verifier, which the phone cannot do for itself", async () => {
    // `verifyLane` re-derives every envelope hash and every payload hash. The
    // probe checks linkage only — re-derivation needs a JSON parser it does not
    // have — so this is a check the phone structurally cannot perform on its own
    // history, over real output rather than a fixture.
    const events = parseExport(await fixture());
    assert.doesNotThrow(() => verifyLane(events));
  });

  test("one altered byte in a payload is rejected", async () => {
    // The check earning its place. An edited payload still parses, still links,
    // and still has a plausible hash chain — the probe's own verifier would pass
    // it, because it checks linkage only. Re-derivation is what catches this,
    // and this is it catching a real edit to real Java output.
    const j = await journal();
    const tampered = (await fixture()).replace("com.unknown/.Watcher", "com.unknown/.Watcher2");
    assert.notEqual(tampered, await fixture(), "the fixture must actually contain the string");

    await assert.rejects(() => importExport(j, tampered), /payload does not match/);
    assert.equal((await j.readLane("grants")).length, 0, "and nothing is kept");
  });

  test("a line that is not JSON fails the whole import, and says which", async () => {
    // A partly-imported chain is the known-absence problem at its worst: a gap
    // that looks like history.
    const text = (await fixture()).split("\n");
    text.splice(2, 0, "{not json");
    assert.throws(() => parseExport(text.join("\n")), ImportError);
    assert.throws(() => parseExport(text.join("\n")), /line 3/);
  });

  test("a line that parses but is not an envelope is refused too", async () => {
    assert.throws(() => parseExport('{"hello":"world"}'), /not an event envelope/);
  });
});

describe("replication, then observation", () => {
  test("the phone's lane arrives verbatim and this device's lane gains Observations", async () => {
    const j = await journal();
    const result = await importExport(j, await fixture());

    assert.deepEqual(result.lanes, ["grants"]);
    assert.equal(result.replicated, 4);
    // Three readings, one per `grants.observed`. The process.start is not one.
    assert.equal(result.observed, 3);

    const replica = await j.readLane("grants");
    assert.equal(replica.length, 4);
    assert.equal(replica.filter((e) => e.type === GRANTS_OBSERVED_TYPE).length, 3);

    const mine = await j.readLane("mac");
    const observations = mine.filter((event) => readObservation(event) !== null);
    assert.equal(observations.length, 3);
    // inv. 3: what perceived it was pass 2 on the phone, not the importer.
    assert.equal(readObservation(observations[0]!)?.source, "pass2@Pixel 10a/stallion");
  });

  test("each Observation cites the phone's own event", async () => {
    const j = await journal();
    await importExport(j, await fixture());

    const readings = (await j.readLane("grants")).filter((e) => e.type === GRANTS_OBSERVED_TYPE);
    const cited = new Set(
      (await j.readLane("mac"))
        .filter((event) => readObservation(event) !== null)
        .flatMap((event) => [...(event.causes ?? [])]),
    );
    for (const reading of readings) {
      assert.equal(cited.has(reading.id), true, `${reading.id} is cited`);
    }
  });

  test("importing the same export twice changes nothing", async () => {
    // Which is what the operator will actually do: every export contains the
    // whole journal from the beginning.
    const j = await journal();
    await importExport(j, await fixture());
    const again = await importExport(j, await fixture());

    assert.equal(again.replicated, 0);
    assert.equal(again.observed, 0);
    assert.equal((await j.readLane("grants")).length, 4);
  });

  test("a longer export of the same lane adds only its tail", async () => {
    const j = await journal();
    const lines = (await fixture()).trimEnd().split("\n");
    await importExport(j, lines.slice(0, 2).join("\n"));
    const rest = await importExport(j, lines.join("\n"));

    assert.equal(rest.replicated, 2);
    assert.equal((await j.readLane("grants")).length, 4);
  });
});

describe("the readings are the ones pass 2 wrote", () => {
  test("a colon-joined holding set comes back as a list", async () => {
    const j = await journal();
    await importExport(j, await fixture());

    const readings = (await j.readLane("mac"))
      .map((event) => readObservation<DeviceAuthorityReading>(event))
      .filter((o) => o !== null);

    const first = readings[0]?.data.kinds.find((k) => k.kind === "accessibility");
    assert.deepEqual(first?.holding, ["app.orb/app.actionlock.guard.PayGuardService"]);
    assert.equal(first?.baseline, true);

    // Two entries, on purpose. A one-element set cannot tell splitting from not
    // splitting — the joined string and the single-element list are the same
    // thing — so the assertion above passes whether or not the split happens.
    // This is the one that fails when it does not.
    const second = readings[1]?.data.kinds.find((k) => k.kind === "accessibility");
    assert.deepEqual(second?.holding, [
      "app.orb/app.actionlock.guard.PayGuardService",
      "com.unknown/.Watcher",
    ]);
    assert.equal(second?.holding?.length, 2, "split, not one string with a colon in it");
  });

  test("an unreadable kind arrives unreadable, never as none", async () => {
    const j = await journal();
    await importExport(j, await fixture());

    const readings = (await j.readLane("mac"))
      .map((event) => readObservation<DeviceAuthorityReading>(event))
      .filter((o) => o !== null);
    const last = readings.at(-1);
    const accessibility = last?.data.kinds.find((k) => k.kind === "accessibility");

    assert.equal(accessibility?.readable, false);
    assert.equal(accessibility?.holding, undefined, "not an empty list");
  });
});

describe("the loop, end to end, on the phone's own bytes", () => {
  test("a grant that appeared on the phone raises exactly one alert here", async () => {
    // Journal → Observation → projection → rule → alert, over a file the Java
    // implementation wrote. The first time the whole loop runs on something this
    // runtime did not produce.
    const j = await journal();
    await importExport(j, await fixture());

    const raised = await raiseAlerts(j);
    const gains = raised.map((event) => event.payload as AlertRaised);

    assert.equal(
      gains.some((alert) => alert.kind === "accessibility" && alert.gained.includes("com.unknown/.Watcher")),
      true,
      "the watcher that appeared is surfaced",
    );
    // The baseline reading raises nothing, and neither does the unreadable kind.
    assert.equal(raised.length, 1);

    assert.equal((await raiseAlerts(j)).length, 0, "and not again");
  });

  test("re-importing after an alert does not re-raise it", async () => {
    const j = await journal();
    await importExport(j, await fixture());
    await raiseAlerts(j);

    await importExport(j, await fixture());
    assert.equal(alertsFor(project(await j.readAll())).length, 0);
  });
});
