/**
 * The share sensor's path into an Observation — `docs/SENSOR_SHARE.md` §4a.
 *
 * The fixture is **generated by `Shares.java.in`, the class the phone runs**
 * (`tools/gen-share-export.sh`), for the reason the grants fixture is: a
 * hand-written one would agree with this reader by construction and prove nothing
 * about the pair. Only the inputs are synthetic.
 */
import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { Journal, MemoryJournalStore, unwrapPayload, verifyLane } from "@orb/journal";
import { readObservation, type Observation } from "@orb/observation";
import {
  SHARED_TYPE,
  SHARE_FIELDS_ATTACHED,
  SHARE_FIELDS_EXCLUDED,
  SHARE_FIELDS_MAPPED,
  alertsFor,
  importExport,
  parseExport,
  project,
  shareFrom,
  type ShareReading,
} from "../src/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixture = () => readFile(join(here, "../../tests/fixtures/share-export.txt"), "utf8");
const INSTALL = "orb-000000000000000000000001";

async function desk() {
  return Journal.open({ lane: "mac", device: "mac-01", store: new MemoryJournalStore() });
}

/** Every Observation in the desk's lane, with the share reading it carries. */
async function shares(journal: Journal): Promise<readonly Observation<ShareReading>[]> {
  const out: Observation<ShareReading>[] = [];
  for (const event of await journal.readLane("mac")) {
    const observation = readObservation(event);
    if (observation !== null) out.push(observation as Observation<ShareReading>);
  }
  return out;
}

describe("an export written by the phone's share code", () => {
  test("verifies under the TypeScript verifier, and holds six shares and one non-share", async () => {
    const events = parseExport(await fixture());
    assert.doesNotThrow(() => verifyLane(events));
    assert.equal(events.filter((event) => event.type === SHARED_TYPE).length, 6);
    assert.equal(events.filter((event) => event.type === "orb.process.start").length, 1);
  });
});

describe("each share becomes one Observation, and nothing else does", () => {
  test("six shares are observed; the process start is not, and stays in the replica", async () => {
    const j = await desk();
    const result = await importExport(j, await fixture());

    assert.equal(result.replicated, 7);
    assert.equal(result.observed, 6, "runtime activity is an Event, not an Observation");
    assert.equal((await shares(j)).length, 6);
    assert.equal((await j.readLane(INSTALL)).length, 7, "the phone's lane arrives whole");
  });

  test("the source is the sensor at the install, the occurrence is certain, and the phone's event is cited", async () => {
    const j = await desk();
    await importExport(j, await fixture());

    const phone = (await j.readLane(INSTALL)).filter((event) => event.type === SHARED_TYPE);
    const mine = (await j.readLane("mac")).filter((event) => readObservation(event) !== null);
    assert.equal(mine.length, phone.length);

    for (const [index, event] of mine.entries()) {
      const observation = readObservation(event)!;
      assert.equal(observation.source, `orb.sensor.share@${INSTALL}`);
      assert.equal(observation.confidencePercent, 100, "the occurrence, never the content");
      assert.deepEqual(event.causes, [phone[index]!.id], "lineage is in causes, not only prose");
    }
  });

  test("a share the phone could not read is still an observation, and says so", async () => {
    const j = await desk();
    await importExport(j, await fixture());
    const unreadable = (await shares(j)).at(-1)!;
    // Not "nothing was shared": the hand-off happened and the intent was unreadable.
    assert.deepEqual(unreadable.data, { because: "user.shared", shareReadable: false });
    assert.equal(unreadable.attachments, undefined);
  });
});

describe("what a share carries", () => {
  const byOutcome = async () => {
    const j = await desk();
    await importExport(j, await fixture());
    return await shares(j);
  };

  test("an unresolved share keeps `resolved: false` and its reason", async () => {
    const [unresolved] = await byOutcome();
    assert.equal(unresolved!.data.resolved, false);
    assert.equal(unresolved!.data.absenceReason, "unfetched");
    assert.equal(unresolved!.attachments, undefined);
  });

  test("a refused grant is a finding, recorded with its detail", async () => {
    const refused = (await byOutcome())[1]!;
    assert.equal(refused.data.resolveOutcome, "refused");
    assert.match(refused.data.resolveDetail ?? "", /Permission Denial/);
    assert.equal(refused.data.resolved, false);
  });

  test("stored content is referenced by identity, never copied into data", async () => {
    const held = (await byOutcome())[2]!;
    assert.deepEqual(held.attachments, [
      "sha256:00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff",
    ]);
    assert.equal(held.data.resolved, true);
    assert.equal(held.data.attachmentBytes, 3642498);
    assert.equal(held.data.absenceReason, undefined, "the content is here now");
    assert.ok(!("attachment" in held.data), "inv. 5: the identity belongs in `attachments`");
  });

  test("several items keep the phone's joined string whole, and the count beside it", async () => {
    const several = (await byOutcome())[3]!;
    assert.equal(several.data.itemCount, 3);
    assert.equal(
      several.data.references,
      "content://com.example.gallery.provider/0/1/photo-4:" +
        "content://com.example.gallery.provider/0/1/photo-5:" +
        "content://com.example.gallery.provider/0/1/photo-6",
    );
    assert.equal(several.data.action, "android.intent.action.SEND_MULTIPLE");
  });

  test("a text share is carried as the text itself, colons and all, with no referrer invented", async () => {
    const text = (await byOutcome())[4]!;
    assert.equal(text.data.references, "Meeting with Ravi is Friday: 3:00 pm");
    assert.equal(text.data.referrer, "unknown", "unknown is recorded, never omitted or guessed");
    assert.equal(text.data.mimeType, "text/plain");
    assert.equal(text.attachments, undefined);
  });

  test("the referrer is carried as data, not promoted to the source", async () => {
    // The sensor is the doorway; the sending app is where it came from. Whether
    // two shares from different apps are independent is AD-6's question, and is
    // not answered by renaming the source.
    const first = (await byOutcome())[0]!;
    assert.equal(first.data.referrer, "android-app://com.example.gallery");
    assert.equal(first.source, `orb.sensor.share@${INSTALL}`);
  });
});

describe("importing again", () => {
  test("the same file twice changes nothing", async () => {
    const j = await desk();
    await importExport(j, await fixture());
    const again = await importExport(j, await fixture());
    assert.equal(again.replicated, 0);
    assert.equal(again.observed, 0);
    assert.equal((await shares(j)).length, 6);
  });

  test("a longer export of the same lane adds only its tail", async () => {
    const lines = (await fixture()).split("\n").filter((line) => line.trim() !== "");
    const j = await desk();

    const early = await importExport(j, lines.slice(0, 4).join("\n") + "\n");
    assert.equal(early.replicated, 4);
    assert.equal(early.observed, 3, "three shares in the first four events");

    const full = await importExport(j, lines.join("\n") + "\n");
    assert.equal(full.replicated, 3);
    assert.equal(full.observed, 3);
    assert.equal((await shares(j)).length, 6);
  });
});

describe("the mapping accounts for every field the phone writes", () => {
  const accounted = new Set<string>([
    ...SHARE_FIELDS_MAPPED,
    ...SHARE_FIELDS_ATTACHED,
    ...SHARE_FIELDS_EXCLUDED,
  ]);

  test("no field in the fixture is left undecided", async () => {
    const seen = new Set<string>();
    for (const event of parseExport(await fixture())) {
      if (event.type !== SHARED_TYPE) continue;
      const payload = (event as { payload: Record<string, unknown> }).payload;
      for (const key of Object.keys(payload)) seen.add(key);
    }
    for (const key of seen) assert.ok(accounted.has(key), `the phone writes "${key}" and the importer has not decided what to do with it`);
  });

  test("nor is one that the Java writes and the fixture happens not to contain", async () => {
    // The fixture only holds what its inputs reached. The source is the record of
    // everything `Shares` can write, so a field added there fails here until it is
    // mapped, attached or excluded on purpose.
    const source = await readFile(
      join(here, "../../../../apps/pixel/orb/src/Shares.java.in"),
      "utf8",
    );
    const written = new Set([...source.matchAll(/payload\.put\("([A-Za-z]+)"/g)].map((match) => match[1]!));
    assert.ok(written.size >= 12, `expected to find the phone's fields, found ${written.size}`);
    for (const key of written) {
      assert.ok(accounted.has(key), `Shares.java.in writes "${key}" and the importer has not decided what to do with it`);
    }
  });

  test("and nothing is accounted for that the phone does not write", async () => {
    const source = await readFile(
      join(here, "../../../../apps/pixel/orb/src/Shares.java.in"),
      "utf8",
    );
    const written = new Set([...source.matchAll(/payload\.put\("([A-Za-z]+)"/g)].map((match) => match[1]!));
    // `elapsedRealtimeMs` is stamped by ShareActivity, not by Shares.
    written.add("elapsedRealtimeMs");
    for (const key of accounted) assert.ok(written.has(key), `"${key}" is mapped but the phone never writes it`);
  });
});

describe("shares and grants readings share a lane without disturbing each other", () => {
  const grants = () => readFile(join(here, "../../tests/fixtures/pass2-export.txt"), "utf8");

  test("the grants projection ignores share Observations, and the alerts it raises are unchanged", async () => {
    const alone = await desk();
    await importExport(alone, await grants());
    const expected = alertsFor(project(await alone.readAll())).length;
    assert.ok(expected > 0, "the grants fixture must raise alerts for this to mean anything");

    const both = await desk();
    await importExport(both, await grants());
    await importExport(both, await fixture());
    const state = project(await both.readAll());
    assert.equal(alertsFor(state).length, expected);
    assert.equal((await shares(both)).length, 6 + 4, "six shares beside the four grants readings");
  });
});

describe("every source follows the one convention", () => {
  const grants = () => readFile(join(here, "../../tests/fixtures/pass2-export.txt"), "utf8");

  test("a source is `orb.sensor.<name>@<device>` — a sensor at an install, never an app", async () => {
    const j = await desk();
    await importExport(j, await grants());
    await importExport(j, await fixture());

    const sources = new Set((await shares(j)).map((observation) => observation.source));
    assert.deepEqual(
      [...sources].sort(),
      [`orb.sensor.grants@Pixel 10a/stallion`, `orb.sensor.share@${INSTALL}`],
    );
    for (const source of sources) {
      assert.match(source, /^orb\.sensor\.[a-z]+@.+$/);
      assert.ok(!source.startsWith("pass"), "the label named a retired app");
    }
  });
});

describe("a payload that is not usable", () => {
  test("not an object is skipped rather than recorded as an empty share", () => {
    assert.equal(shareFrom(null), null);
    assert.equal(shareFrom("orb.shared"), null);
  });

  test("a field of the wrong type is left out, never coerced", () => {
    const share = shareFrom({ because: "user.shared", resolved: "yes", itemCount: "3", attachment: "not an identity" });
    assert.deepEqual(share, { data: { because: "user.shared" }, attachments: [] });
  });

  test("a missing reason is `unknown`, not an invented one", () => {
    assert.equal(shareFrom({})?.data.because, "unknown");
  });
});

describe("the process start names the build that wrote it", () => {
  test("the phone's own record carries a numeric versionCode and a versionName", async () => {
    const start = parseExport(await fixture()).find((event) => event.type === "orb.process.start")!;
    const payload = unwrapPayload(start.payload) as Record<string, unknown>;
    assert.equal(typeof payload["versionCode"], "number");
    assert.equal(typeof payload["versionName"], "string");
  });

  test("and the app builds that record through Start, so the fixture and the phone cannot differ", async () => {
    const orb = await readFile(join(here, "../../../../apps/pixel/orb/src/Orb.java.in"), "utf8");
    assert.match(orb, /Start\.record\(/);
    // Nothing else writes the start event's fields by hand.
    assert.doesNotMatch(orb, /payload\.put\("androidRelease"/);
  });

  test("an unreadable version is -1, never 0 and never absent", async () => {
    const start = await readFile(join(here, "../../../../apps/pixel/orb/src/Start.java.in"), "utf8");
    assert.match(start, /VERSION_UNREADABLE\s*=\s*-1L/);
    const orb = await readFile(join(here, "../../../../apps/pixel/orb/src/Orb.java.in"), "utf8");
    assert.match(orb, /long versionCode = Start\.VERSION_UNREADABLE/);
  });
});
